### ISSUE TITLE
Wrong initialization, reseting...

### ISSUE THREAD

**Issue by antithing** [b51/ceres_mono_orb_slam2#1] opened 2019-10-25 14:05 UTC
Hi! And thank you for making this code available.

I have it built, but when i run the slam never initialises, giving me either:

` std::cout << "Wrong initialization, reseting..." << std::endl;`

or:

` std::cout << "Track lost soon after initialisation, reseting..."`

I am using the desk1 dataset with TUM1.yaml. 

I have tried different linear_solver_types also, but I get the same result.

Thanks!

**Comment by b51** [comment] 2019-10-26 02:32
Thanks for ur feedback, I only tested this on rgbd_dataset_freiburg2_desk with TUM2.yaml and didn't meet that problem. I'll download deskt1 dataset to have some tests on it and will notify u if I fixed it. BTW, this repo hasn't complete yet, according to my test, it has some problem at function CeresOptimizer::OptimizeEssentialGraph for global ba optimazation,  run with dataset like kitti will cause some problem after loop closing and I'm trying to fix it.

**Comment by b51** [comment] 2019-10-26 03:51
@antithing  I tested on the rgbd_dataset_freiburg1_desk1 dataset with TUM1.yaml with my code and original ORB_SLAM2, initialization may failed sometimes at first, but always initialize successed after some try. 

`"Wrong initialization, resetting..."` is caused by tracked map points less than threshold 100 setted at src/Tracking.cc line 508:` if (median_depth < 0 || current_keyframe->TrackedMapPoint(1) < 100)`. According to my experience on desk1 dataset, decrease 100 to 80 or lower to make initialize more likely to success. The number of tracked map points is shown with info `"New Map created with xx points"` xx is the number of tracked map points, you might check this to get a reasonable threshold.

`"Track lost soon after initialisation, reseting..."` I tested serveral times and have't encounter this error yet. I'll keep my eyes on it in the future

**Closed as completed** 2019-11-08 02:34 UTC
